### PR TITLE
Return user on login

### PR DESCRIPTION
**Pull request by felixheidecke**
`oc.login(…)` now returns the user object instead of simply returning `true`

Referring to: https://github.com/owncloud/js-owncloud-client/issues/59

### CODE REVIEW

**Comment by PVince81** [comment]
please also adjust the unit tests

**Comment by PVince81** [comment]
tests are failing because `'true'` is not `true`, didn't you fix this elsewhere?

**Comment by felixheidecke** [comment]
@PVince81 I tried fixing it in https://github.com/owncloud/js-owncloud-client/pull/64 but local testing always fails on my Mac and Linux machine. Oshan didn't have any luck as well so I postponed.

Have you tried checking out the master and run `make test` ?

**Comment by DeepDiver1975** [comment]
implemented in #100

**Pull request closed without merging**
